[package]
name = "wldmania"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2024"

[dependencies]
clap = {version = "4.5", features = ["derive"]}
ansi_term = "0.12.1"
rand = "0.9"
terraria-wld = { path = "terraria-wld" }
terraria-strings = { path = "terraria-strings" }

[workspace]
members = ["terraria-wld", "terraria-strings", "wldview"]

[profile.dev]
debug = "line-tables-only"
opt-level = 1
