[package]
name = "wldmania"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
byteorder = "1.4.3"
clap = "2.33.3"
ansi_term = "0.12.1"
bidir-map = "1.0.0"
rand = "0.8.4"
