[package]
name = "wldmania"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
toml = "0.4.5"
serde_derive = "*"
serde = "*"
byteorder = "1.1.0"
clap = "2.26.2"
ansi_term = "0.10.2"
