[package]
name = "wldmania"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
byteorder = "1.1.0"
clap = "2.26.2"
ansi_term = "0.11.0"
bidir-map = "1.0.0"
rand = "0.5.0"
