[package]
name = "wldmania"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
toml = "0.4.5"
byteorder = "1.1.0"
clap = "2.26.2"
ansi_term = "0.10.2"
csv = "1.0.0-beta.5"
bidir-map = "1.0.0"
rand = "0.4.2"
