[package]
name = "wldmanip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-macroquad = "0.9.0"
rfd = "0.8.1"
terraria-wld = { path = "../terraria-wld" }
